### ISSUE TITLE
Requesting for Attachment

### ISSUE THREAD

**Issue by Kavipriya1996** [Kavi96/Whatsup_Document#6]
Dear Kavi96,

You are doing a great job. Please help to add the documents of any type in your attachment code

**Comment by Kavi96** [comment]
Dear Kavipriya1996,

Thanks for suggesting, will modify the code

**Comment by Kavi96** [comment]
Dear Kavipriya1996,

Thanks for your valuable suggestions. This feature is going to make our product good
